-- Neymar Jr Archive + Supabase
-- Cole este arquivo no SQL Editor do Supabase e execute.
-- Ele cria as tabelas, habilita RLS e popula os dados iniciais do site.

create extension if not exists pgcrypto;

create table if not exists public.neymar_profile (
  id smallint primary key default 1,
  name text not null,
  short_name text,
  birth text,
  birthplace text,
  position text,
  height text,
  dominant_foot text,
  hero_image text,
  subtitle text,
  updated_at_label text,
  updated_at timestamptz default now()
);

create table if not exists public.neymar_totals (
  id bigint generated by default as identity primary key,
  sort_order int default 0,
  label text not null,
  value numeric not null,
  suffix text default '',
  note text
);

create table if not exists public.neymar_goal_types (
  id bigint generated by default as identity primary key,
  sort_order int default 0,
  type text not null,
  value numeric not null,
  source text,
  description text
);

create table if not exists public.neymar_club_passages (
  id bigint generated by default as identity primary key,
  sort_order int default 0,
  slug text unique,
  club text not null,
  period text,
  country text,
  role text,
  shirt text,
  image text,
  summary text,
  games int default 0,
  goals int default 0,
  assists int default 0,
  penalties int default 0,
  free_kicks int default 0,
  highlights jsonb default '[]'::jsonb,
  titles jsonb default '[]'::jsonb,
  important_games jsonb default '[]'::jsonb
);

create table if not exists public.neymar_national_teams (
  id bigint generated by default as identity primary key,
  sort_order int default 0,
  team text not null,
  period text,
  games int default 0,
  goals int default 0,
  titles jsonb default '[]'::jsonb,
  note text
);

create table if not exists public.neymar_collective_titles (
  id bigint generated by default as identity primary key,
  sort_order int default 0,
  category text not null,
  title text not null,
  years text,
  image text
);

create table if not exists public.neymar_individual_awards (
  id bigint generated by default as identity primary key,
  sort_order int default 0,
  classification text not null,
  title text not null,
  years text,
  image text,
  detail text
);

create table if not exists public.neymar_important_goals (
  id bigint generated by default as identity primary key,
  sort_order int default 0,
  classification text,
  competition text,
  type text,
  opponent text,
  date_label text,
  detail text
);

create table if not exists public.neymar_opponents (
  id bigint generated by default as identity primary key,
  sort_order int default 0,
  name text not null,
  category text,
  context text,
  goals int default 0
);

create table if not exists public.neymar_gallery (
  id bigint generated by default as identity primary key,
  sort_order int default 0,
  title text not null,
  tag text,
  image text,
  credit text
);

create table if not exists public.neymar_sources (
  id bigint generated by default as identity primary key,
  sort_order int default 0,
  label text not null,
  url text not null
);

create table if not exists public.site_feedback (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz default now(),
  name text,
  email text,
  category text,
  source_url text,
  message text not null,
  page text,
  path text,
  status text default 'novo'
);

create table if not exists public.site_page_views (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz default now(),
  page text,
  path text,
  referrer text,
  user_agent text
);

-- RLS: leitura pública apenas das tabelas de conteúdo.

alter table public.neymar_profile enable row level security;
drop policy if exists "Public read neymar_profile" on public.neymar_profile;
create policy "Public read neymar_profile" on public.neymar_profile for select to anon, authenticated using (true);

alter table public.neymar_totals enable row level security;
drop policy if exists "Public read neymar_totals" on public.neymar_totals;
create policy "Public read neymar_totals" on public.neymar_totals for select to anon, authenticated using (true);

alter table public.neymar_goal_types enable row level security;
drop policy if exists "Public read neymar_goal_types" on public.neymar_goal_types;
create policy "Public read neymar_goal_types" on public.neymar_goal_types for select to anon, authenticated using (true);

alter table public.neymar_club_passages enable row level security;
drop policy if exists "Public read neymar_club_passages" on public.neymar_club_passages;
create policy "Public read neymar_club_passages" on public.neymar_club_passages for select to anon, authenticated using (true);

alter table public.neymar_national_teams enable row level security;
drop policy if exists "Public read neymar_national_teams" on public.neymar_national_teams;
create policy "Public read neymar_national_teams" on public.neymar_national_teams for select to anon, authenticated using (true);

alter table public.neymar_collective_titles enable row level security;
drop policy if exists "Public read neymar_collective_titles" on public.neymar_collective_titles;
create policy "Public read neymar_collective_titles" on public.neymar_collective_titles for select to anon, authenticated using (true);

alter table public.neymar_individual_awards enable row level security;
drop policy if exists "Public read neymar_individual_awards" on public.neymar_individual_awards;
create policy "Public read neymar_individual_awards" on public.neymar_individual_awards for select to anon, authenticated using (true);

alter table public.neymar_important_goals enable row level security;
drop policy if exists "Public read neymar_important_goals" on public.neymar_important_goals;
create policy "Public read neymar_important_goals" on public.neymar_important_goals for select to anon, authenticated using (true);

alter table public.neymar_opponents enable row level security;
drop policy if exists "Public read neymar_opponents" on public.neymar_opponents;
create policy "Public read neymar_opponents" on public.neymar_opponents for select to anon, authenticated using (true);

alter table public.neymar_gallery enable row level security;
drop policy if exists "Public read neymar_gallery" on public.neymar_gallery;
create policy "Public read neymar_gallery" on public.neymar_gallery for select to anon, authenticated using (true);

alter table public.neymar_sources enable row level security;
drop policy if exists "Public read neymar_sources" on public.neymar_sources;
create policy "Public read neymar_sources" on public.neymar_sources for select to anon, authenticated using (true);

alter table public.site_feedback enable row level security;
alter table public.site_page_views enable row level security;
drop policy if exists "Public insert site_feedback" on public.site_feedback;
create policy "Public insert site_feedback" on public.site_feedback for insert to anon, authenticated with check (true);
drop policy if exists "Public insert site_page_views" on public.site_page_views;
create policy "Public insert site_page_views" on public.site_page_views for insert to anon, authenticated with check (true);

-- Dados iniciais. Se rodar novamente, as tabelas de conteúdo são recarregadas.
truncate table public.neymar_profile, public.neymar_totals, public.neymar_goal_types, public.neymar_club_passages, public.neymar_national_teams, public.neymar_collective_titles, public.neymar_individual_awards, public.neymar_important_goals, public.neymar_opponents, public.neymar_gallery, public.neymar_sources restart identity cascade;

insert into public.neymar_profile (id,name,short_name,birth,birthplace,position,height,dominant_foot,hero_image,subtitle,updated_at_label) values (1,'Neymar da Silva Santos Júnior','Neymar Jr.','05/02/1992','Mogi das Cruzes, Brasil','Atacante / Meia-atacante','1,75 m','Destro','https://commons.wikimedia.org/wiki/Special:FilePath/Neymar%20-%20FC%20Barcelona%20-%202015.jpg','Arquivo premium da carreira: clubes, Seleção, gols, títulos, medalhas e prêmios.','08/07/2026');
insert into public.neymar_totals (sort_order,label,value,suffix,note) values (1,'Gols pela Seleção',80,'+','Base Transfermarkt, caps/gols da página de conquistas');
insert into public.neymar_totals (sort_order,label,value,suffix,note) values (2,'Pênaltis convertidos',94,'','Transfermarkt: total de pênaltis marcados');
insert into public.neymar_totals (sort_order,label,value,suffix,note) values (3,'Faltas diretas',14,'','StatBunker: direct free kick em competições cobertas');
insert into public.neymar_totals (sort_order,label,value,suffix,note) values (4,'Títulos coletivos listados',28,'+','Clubes + Seleção, variando por critério');
insert into public.neymar_goal_types (sort_order,type,value,source,description) values (1,'Pênalti',94,'Transfermarkt','Pênaltis convertidos na carreira profissional, incluindo clubes e Seleção.');
insert into public.neymar_goal_types (sort_order,type,value,source,description) values (2,'Pênaltis perdidos',22,'Transfermarkt','Cobranças não convertidas, conforme registro público por jogo.');
insert into public.neymar_goal_types (sort_order,type,value,source,description) values (3,'Falta direta',14,'StatBunker','Gols de falta direta em competições cobertas pelo StatBunker.');
insert into public.neymar_goal_types (sort_order,type,value,source,description) values (4,'Pé direito',160,'StatBunker','Gols com o pé direito em competições cobertas.');
insert into public.neymar_goal_types (sort_order,type,value,source,description) values (5,'Pé esquerdo',61,'StatBunker','Gols com o pé esquerdo em competições cobertas.');
insert into public.neymar_goal_types (sort_order,type,value,source,description) values (6,'Cabeça',9,'StatBunker','Gols de cabeça em competições cobertas.');
insert into public.neymar_club_passages (sort_order,slug,club,period,country,role,shirt,image,summary,games,goals,assists,penalties,free_kicks,highlights,titles,important_games) values (1,'santos-1','Santos FC','2009–2013','Brasil','Revelação, protagonista e campeão continental','11','https://commons.wikimedia.org/wiki/Special:FilePath/Neymar%20Junior%20the%20Future%20of%20Brazil%202.jpg','Surgiu como fenômeno no Santos, decidiu mata-matas, liderou geração campeã da Libertadores e consolidou-se como maior promessa brasileira do período.',225,136,64,20,4,'["Estreia profissional em 2009.", "Campeão da Copa do Brasil 2010 com artilharia da competição.", "Campeão da Libertadores 2011, encerrando jejum histórico do Santos.", "Gol que venceu o Prêmio Puskás 2011 contra o Flamengo.", "Eleito melhor jogador sul-americano em 2011 e 2012."]'::jsonb,'["Campeonato Paulista 2010, 2011 e 2012", "Copa do Brasil 2010", "Copa Libertadores 2011", "Recopa Sul-Americana 2012"]'::jsonb,'[{"date": "27/07/2011", "title": "Santos x Flamengo", "detail": "Gol antológico que rendeu o FIFA Puskás Award de 2011."}, {"date": "22/06/2011", "title": "Santos x Peñarol", "detail": "Final da Libertadores 2011; Neymar marcou na decisão."}, {"date": "2010", "title": "Copa do Brasil", "detail": "Artilheiro com 11 gols e campeão nacional."}]'::jsonb);
insert into public.neymar_club_passages (sort_order,slug,club,period,country,role,shirt,image,summary,games,goals,assists,penalties,free_kicks,highlights,titles,important_games) values (2,'barcelona','FC Barcelona','2013–2017','Espanha','Trio MSN, auge europeu e Champions League','11','https://commons.wikimedia.org/wiki/Special:FilePath/Neymar%20-%20FC%20Barcelona%20-%202015.jpg','No Barcelona, Neymar viveu seu auge europeu. Formou o trio MSN com Messi e Suárez, venceu a Champions e decidiu jogos gigantes.',186,105,76,10,5,'["Chegada oficial em 2013 e adaptação ao futebol europeu.", "Temporada 2014/15 histórica com Champions, La Liga e Copa do Rei.", "Artilheiro da Champions 2014/15 ao lado de Messi e Cristiano Ronaldo, com 10 gols.", "Gol na final da Champions contra a Juventus em Berlim.", "Protagonista da remontada contra o PSG em 2017."]'::jsonb,'["La Liga 2014/15 e 2015/16", "Copa do Rei 2014/15, 2015/16 e 2016/17", "Champions League 2014/15", "Mundial de Clubes 2015", "Supercopa da Espanha 2013"]'::jsonb,'[{"date": "06/06/2015", "title": "Barcelona 3 x 1 Juventus", "detail": "Gol no fim da final da Champions League 2014/15."}, {"date": "08/03/2017", "title": "Barcelona 6 x 1 PSG", "detail": "Dois gols e uma assistência na remontada histórica."}, {"date": "21/04/2015", "title": "Barcelona x PSG", "detail": "Dois gols nas quartas da Champions."}]'::jsonb);
insert into public.neymar_club_passages (sort_order,slug,club,period,country,role,shirt,image,summary,games,goals,assists,penalties,free_kicks,highlights,titles,important_games) values (3,'psg','Paris Saint-Germain','2017–2023','França','Transferência recorde, camisa 10 e final europeia','10','https://commons.wikimedia.org/wiki/Special:FilePath/Neymar%20PSG.jpg','Contratação mais cara da história, Neymar levou criatividade e decisão ao PSG, conquistou títulos nacionais e chegou à final da Champions em 2020.',173,118,77,24,7,'["Transferência recorde mundial em 2017.", "Eleito melhor jogador da Ligue 1 em 2017/18.", "Conduziu o PSG à primeira final de Champions League do clube em 2020.", "Passou dos 100 gols pelo PSG.", "Quarto maior artilheiro da história do clube no período."]'::jsonb,'["Ligue 1 2017/18, 2018/19, 2019/20, 2021/22 e 2022/23", "Copa da França 2017/18, 2019/20 e 2020/21", "Copa da Liga Francesa 2017/18 e 2019/20", "Supercopa da França 2018, 2020 e 2022"]'::jsonb,'[{"date": "2020", "title": "PSG na final da Champions", "detail": "Participação central na campanha europeia histórica do clube."}, {"date": "02/12/2020", "title": "Manchester United x PSG", "detail": "Atuação decisiva com gols em Old Trafford."}, {"date": "2018", "title": "Primeira temporada", "detail": "Temporada de impacto com título francês e prêmio de jogador do ano."}]'::jsonb);
insert into public.neymar_club_passages (sort_order,slug,club,period,country,role,shirt,image,summary,games,goals,assists,penalties,free_kicks,highlights,titles,important_games) values (4,'alhilal','Al-Hilal SFC','2023–2025','Arábia Saudita','Projeto saudita e título nacional','10','https://commons.wikimedia.org/wiki/Special:FilePath/Neymar%20Al-Hilal%20SFC%202023.jpg','Passagem marcada por alta expectativa, lesão grave e participação reduzida. Ainda assim, integrou elenco campeão saudita.',7,1,3,0,0,'["Chegada ao futebol saudita em 2023.", "Primeiro gol pelo clube em competição asiática.", "Campeão saudita 2023/24 com o Al-Hilal.", "Lesão no joelho reduziu drasticamente sua sequência."]'::jsonb,'["Saudi Pro League 2023/24"]'::jsonb,'[{"date": "03/10/2023", "title": "Al-Hilal x Nassaji", "detail": "Primeiro gol pelo Al-Hilal."}]'::jsonb);
insert into public.neymar_club_passages (sort_order,slug,club,period,country,role,shirt,image,summary,games,goals,assists,penalties,free_kicks,highlights,titles,important_games) values (5,'santos-2','Santos FC','2025–atual','Brasil','Retorno ao clube formador','10','https://commons.wikimedia.org/wiki/Special:FilePath/Neymar%20Barcelona%20presentation%202.jpg','Retorno ao Santos com status de ídolo máximo contemporâneo, assumindo camisa 10 e função de liderança técnica.',36,15,8,6,1,'["Retorno anunciado após ciclo no exterior.", "Camisa 10 e referência técnica do elenco.", "Nova fase com foco em liderança, protagonismo e recuperação de ritmo."]'::jsonb,'[]'::jsonb,'[{"date": "2025", "title": "Volta à Vila Belmiro", "detail": "Retorno simbólico ao clube que o revelou."}]'::jsonb);
insert into public.neymar_national_teams (sort_order,team,period,games,goals,titles,note) values (1,'Brasil Sub-17','2009',3,1,'[]'::jsonb,'Primeira vitrine internacional de base.');
insert into public.neymar_national_teams (sort_order,team,period,games,goals,titles,note) values (2,'Brasil Sub-20','2011',7,9,'["Sul-Americano Sub-20 2011"]'::jsonb,'Campeão e destaque ofensivo.');
insert into public.neymar_national_teams (sort_order,team,period,games,goals,titles,note) values (3,'Brasil Olímpico / Sub-23','2012–2016',14,8,'["Prata Olímpica 2012", "Ouro Olímpico 2016"]'::jsonb,'Capitão e cobrador decisivo no ouro do Rio 2016.');
insert into public.neymar_national_teams (sort_order,team,period,games,goals,titles,note) values (4,'Seleção Brasileira Principal','2010–2026',130,80,'["Copa das Confederações 2013"]'::jsonb,'Maior artilheiro da história da Seleção Brasileira segundo base Transfermarkt.');
insert into public.neymar_collective_titles (sort_order,category,title,years,image) values (1,'Santos','Campeonato Paulista','2010, 2011, 2012','https://commons.wikimedia.org/wiki/Special:FilePath/Pacaembu%20Santos%202010.jpg');
insert into public.neymar_collective_titles (sort_order,category,title,years,image) values (2,'Santos','Copa do Brasil','2010','https://commons.wikimedia.org/wiki/Special:FilePath/Copa%20do%20Brasil%20trophy.jpg');
insert into public.neymar_collective_titles (sort_order,category,title,years,image) values (3,'Santos','Copa Libertadores','2011','https://commons.wikimedia.org/wiki/Special:FilePath/Trof%C3%A9u%20da%20Copa%20Libertadores%20da%20Am%C3%A9rica%20de%202023.jpg');
insert into public.neymar_collective_titles (sort_order,category,title,years,image) values (4,'Santos','Recopa Sul-Americana','2012','https://commons.wikimedia.org/wiki/Special:FilePath/Copa%20Libertadores%20trophy.jpg');
insert into public.neymar_collective_titles (sort_order,category,title,years,image) values (5,'Barcelona','La Liga','2014/15, 2015/16','https://commons.wikimedia.org/wiki/Special:FilePath/La%20Liga%20trophy%202019.jpg');
insert into public.neymar_collective_titles (sort_order,category,title,years,image) values (6,'Barcelona','Copa do Rei','2014/15, 2015/16, 2016/17','https://commons.wikimedia.org/wiki/Special:FilePath/Copa%20del%20Rey%20Trophy.jpg');
insert into public.neymar_collective_titles (sort_order,category,title,years,image) values (7,'Barcelona','UEFA Champions League','2014/15','https://commons.wikimedia.org/wiki/Special:FilePath/Champions%20League%20Trophy%20%2852736201132%29.jpg');
insert into public.neymar_collective_titles (sort_order,category,title,years,image) values (8,'Barcelona','Mundial de Clubes FIFA','2015','https://commons.wikimedia.org/wiki/Special:FilePath/FIFA%20Club%20World%20Cup%20trophy.jpg');
insert into public.neymar_collective_titles (sort_order,category,title,years,image) values (9,'PSG','Ligue 1','2017/18, 2018/19, 2019/20, 2021/22, 2022/23','https://commons.wikimedia.org/wiki/Special:FilePath/Troph%C3%A9e%20de%20Ligue%201%20Uber%20Eats.jpg');
insert into public.neymar_collective_titles (sort_order,category,title,years,image) values (10,'PSG','Copas nacionais francesas','Coupe de France, Coupe de la Ligue e Supercopas','https://commons.wikimedia.org/wiki/Special:FilePath/Coupe%20de%20France%20Trophy.jpg');
insert into public.neymar_collective_titles (sort_order,category,title,years,image) values (11,'Al-Hilal','Saudi Pro League','2023/24','https://commons.wikimedia.org/wiki/Special:FilePath/Al-Hilal%20SFC%20Logo.svg');
insert into public.neymar_collective_titles (sort_order,category,title,years,image) values (12,'Seleção','Copa das Confederações FIFA','2013','https://commons.wikimedia.org/wiki/Special:FilePath/Confed.Cup2013Champions.jpg');
insert into public.neymar_collective_titles (sort_order,category,title,years,image) values (13,'Seleção','Ouro Olímpico','Rio 2016','https://commons.wikimedia.org/wiki/Special:FilePath/Neymar%20Rio%202016.jpg');
insert into public.neymar_individual_awards (sort_order,classification,title,years,image,detail) values (1,'Prêmio individual','FIFA Puskás Award','2011','https://commons.wikimedia.org/wiki/Special:FilePath/FIFA%20Puskas%20Award%202009%20CR7%20Museum.jpg','Venceu pelo gol contra o Flamengo, marcado pelo Santos em 2011.');
insert into public.neymar_individual_awards (sort_order,classification,title,years,image,detail) values (2,'Prêmio individual','Futebolista Sul-Americano do Ano','2011 e 2012','https://commons.wikimedia.org/wiki/Special:FilePath/Neymar%20Junior%20the%20Future%20of%20Brazil%202.jpg','Reconhecimento continental no período de maior domínio pelo Santos.');
insert into public.neymar_individual_awards (sort_order,classification,title,years,image,detail) values (3,'Prêmio de torneio','Bola de Ouro da Copa das Confederações','2013','https://commons.wikimedia.org/wiki/Special:FilePath/Brasil%20copa%20confedera%C3%A7%C3%B5es2013.jpg','Melhor jogador da competição vencida pelo Brasil.');
insert into public.neymar_individual_awards (sort_order,classification,title,years,image,detail) values (4,'Prêmio individual','Jogador do Ano da Ligue 1','2017/18','https://commons.wikimedia.org/wiki/Special:FilePath/Neymar%20PSG.jpg','Prêmio de melhor jogador do campeonato francês em sua primeira temporada no PSG.');
insert into public.neymar_individual_awards (sort_order,classification,title,years,image,detail) values (5,'Artilharia','Artilheiro da UEFA Champions League','2014/15 — 10 gols','https://commons.wikimedia.org/wiki/Special:FilePath/Champions%20League%20Trophy%20%2852736201132%29.jpg','Dividiu a artilharia com Messi e Cristiano Ronaldo.');
insert into public.neymar_individual_awards (sort_order,classification,title,years,image,detail) values (6,'Artilharia','Artilheiro da Copa do Brasil','2010 — 11 gols','https://commons.wikimedia.org/wiki/Special:FilePath/Neymar%20Junior%20the%20Future%20of%20Brazil%202.jpg','Marcou em campanha campeã do Santos.');
insert into public.neymar_individual_awards (sort_order,classification,title,years,image,detail) values (7,'Artilharia','Artilheiro do Campeonato Paulista','2012 — 20 gols','https://commons.wikimedia.org/wiki/Special:FilePath/Neymar%20Junior%20the%20Future%20of%20Brazil%202.jpg','Temporada de enorme domínio estadual pelo Santos.');
insert into public.neymar_individual_awards (sort_order,classification,title,years,image,detail) values (8,'Artilharia','Artilheiro da Libertadores','2012 — 8 gols','https://commons.wikimedia.org/wiki/Special:FilePath/Trof%C3%A9u%20da%20Copa%20Libertadores%20da%20Am%C3%A9rica%20de%202023.jpg','Destaque ofensivo continental pelo Santos.');
insert into public.neymar_individual_awards (sort_order,classification,title,years,image,detail) values (9,'Medalha','Medalha de Ouro Olímpica','Rio 2016','https://commons.wikimedia.org/wiki/Special:FilePath/Neymar%20Rio%202016.jpg','Capitão do Brasil; marcou falta no tempo normal e converteu o pênalti decisivo na final contra a Alemanha.');
insert into public.neymar_individual_awards (sort_order,classification,title,years,image,detail) values (10,'Medalha','Medalha de Prata Olímpica','Londres 2012','https://commons.wikimedia.org/wiki/Special:FilePath/2012%20Summer%20Olympics%20football%20men%20Brazil%20team.jpg','Vice-campeão olímpico com a Seleção Brasileira Sub-23.');
insert into public.neymar_important_goals (sort_order,classification,competition,type,opponent,date_label,detail) values (1,'Santos','Brasileirão','Gol histórico / Puskás','Flamengo','27/07/2011','Arrancada com dribles em sequência e finalização; vencedor do Puskás.');
insert into public.neymar_important_goals (sort_order,classification,competition,type,opponent,date_label,detail) values (2,'Santos','Libertadores','Jogo corrido','Peñarol','22/06/2011','Gol na final da Libertadores 2011.');
insert into public.neymar_important_goals (sort_order,classification,competition,type,opponent,date_label,detail) values (3,'Barcelona','Champions League','Jogo corrido','Juventus','06/06/2015','Gol no fim da final que confirmou o título europeu.');
insert into public.neymar_important_goals (sort_order,classification,competition,type,opponent,date_label,detail) values (4,'Barcelona','Champions League','Falta + pênalti','PSG','08/03/2017','Dois gols e assistência na remontada de 6 x 1.');
insert into public.neymar_important_goals (sort_order,classification,competition,type,opponent,date_label,detail) values (5,'Seleção','Copa das Confederações','Jogo corrido','Espanha','30/06/2013','Gol na final vencida pelo Brasil no Maracanã.');
insert into public.neymar_important_goals (sort_order,classification,competition,type,opponent,date_label,detail) values (6,'Seleção','Jogos Olímpicos','Falta + pênalti decisivo','Alemanha Olímpica','20/08/2016','Gol de falta e pênalti final no ouro olímpico.');
insert into public.neymar_important_goals (sort_order,classification,competition,type,opponent,date_label,detail) values (7,'PSG','Champions League','Jogo corrido','Manchester United','02/12/2020','Dois gols em vitória decisiva fora de casa.');
insert into public.neymar_important_goals (sort_order,classification,competition,type,opponent,date_label,detail) values (8,'Al-Hilal','AFC Champions League','Jogo corrido','Nassaji Mazandaran','03/10/2023','Primeiro gol pelo Al-Hilal.');
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (1,'Estados Unidos','Seleção','Brasil principal',4);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (2,'Argentina','Seleção','Brasil principal',3);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (3,'México','Seleção','Brasil principal',4);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (4,'Japão','Seleção','Brasil principal',9);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (5,'Colômbia','Seleção','Brasil principal',4);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (6,'Bolívia','Seleção','Brasil principal',5);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (7,'Chile','Seleção','Brasil principal',2);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (8,'Espanha','Seleção','Brasil principal',1);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (9,'Itália','Seleção','Brasil principal',1);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (10,'Croácia','Seleção','Brasil principal',3);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (11,'Cameroon','Seleção','Brasil principal',1);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (12,'Peru','Seleção','Brasil principal',5);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (13,'Equador','Seleção','Brasil principal',2);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (14,'Uruguai','Seleção','Brasil principal',2);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (15,'Paraguai','Seleção','Brasil principal',2);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (16,'Costa Rica','Seleção','Brasil principal',1);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (17,'Áustria','Seleção','Brasil principal',1);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (18,'Coreia do Sul','Seleção','Brasil principal',5);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (19,'Tunísia','Seleção','Brasil principal',1);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (20,'Venezuela','Seleção','Brasil principal',1);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (21,'Gana','Seleção','Brasil principal',1);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (22,'Sérvia','Seleção','Brasil principal',1);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (23,'Honduras Olímpica','Seleção','Brasil Olímpico',1);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (24,'Alemanha Olímpica','Seleção','Brasil Olímpico',1);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (25,'Haiti','Seleção','Copa América Centenário',1);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (26,'Flamengo','Clube brasileiro','Santos',3);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (27,'Palmeiras','Clube brasileiro','Santos',6);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (28,'São Paulo','Clube brasileiro','Santos',5);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (29,'Corinthians','Clube brasileiro','Santos',4);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (30,'Atlético-MG','Clube brasileiro','Santos',3);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (31,'Cruzeiro','Clube brasileiro','Santos',3);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (32,'Grêmio','Clube brasileiro','Santos',2);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (33,'Internacional','Clube brasileiro','Santos',2);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (34,'Fluminense','Clube brasileiro','Santos',2);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (35,'Vasco','Clube brasileiro','Santos',2);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (36,'Botafogo','Clube brasileiro','Santos',2);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (37,'Athletico-PR','Clube brasileiro','Santos',2);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (38,'Ceará','Clube brasileiro','Santos',2);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (39,'Avaí','Clube brasileiro','Santos',2);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (40,'Vitória','Clube brasileiro','Santos',2);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (41,'Mogi Mirim','Clube brasileiro','Santos',1);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (42,'Rio Branco-AC','Clube brasileiro','Santos',1);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (43,'Santo André','Clube brasileiro','Santos',1);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (44,'Guarani','Clube brasileiro','Santos',1);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (45,'Ponte Preta','Clube brasileiro','Santos',1);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (46,'Oeste','Clube brasileiro','Santos',1);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (47,'Ituano','Clube brasileiro','Santos',1);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (48,'Linense','Clube brasileiro','Santos',1);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (49,'Peñarol','Clube sul-americano','Santos / Libertadores',1);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (50,'Cerro Porteño','Clube sul-americano','Santos / Libertadores',2);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (51,'Bolívar','Clube sul-americano','Santos / Libertadores',1);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (52,'The Strongest','Clube sul-americano','Santos / Libertadores',1);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (53,'Vélez Sarsfield','Clube sul-americano','Santos / Libertadores',1);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (54,'Real Madrid','Clube europeu','Barcelona',3);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (55,'Atlético de Madrid','Clube europeu','Barcelona',7);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (56,'Villarreal','Clube europeu','Barcelona',5);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (57,'Juventus','Clube europeu','Barcelona',1);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (58,'PSG','Clube europeu','Barcelona',6);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (59,'Bayern de Munique','Clube europeu','Barcelona',2);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (60,'Manchester City','Clube europeu','Barcelona',4);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (61,'Celtic','Clube europeu','Barcelona / PSG',4);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (62,'Ajax','Clube europeu','Barcelona',3);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (63,'Arsenal','Clube europeu','Barcelona',1);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (64,'Sevilla','Clube europeu','Barcelona',4);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (65,'Athletic Club','Clube europeu','Barcelona',5);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (66,'Espanyol','Clube europeu','Barcelona',3);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (67,'Granada','Clube europeu','Barcelona',3);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (68,'Rayo Vallecano','Clube europeu','Barcelona',4);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (69,'Celta de Vigo','Clube europeu','Barcelona',2);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (70,'Deportivo La Coruña','Clube europeu','Barcelona',2);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (71,'Elche','Clube europeu','Barcelona',3);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (72,'Eibar','Clube europeu','Barcelona',2);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (73,'Getafe','Clube europeu','Barcelona',2);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (74,'Las Palmas','Clube europeu','Barcelona',2);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (75,'Málaga','Clube europeu','Barcelona',1);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (76,'Real Sociedad','Clube europeu','Barcelona',1);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (77,'Borussia Mönchengladbach','Clube europeu','Barcelona',1);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (78,'BATE Borisov','Clube europeu','Barcelona',1);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (79,'Olympique de Marseille','Clube europeu','PSG',3);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (80,'Monaco','Clube europeu','PSG',4);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (81,'Lyon','Clube europeu','PSG',3);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (82,'Lille','Clube europeu','PSG',4);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (83,'Rennes','Clube europeu','PSG',3);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (84,'Nice','Clube europeu','PSG',3);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (85,'Bordeaux','Clube europeu','PSG',4);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (86,'Guingamp','Clube europeu','PSG',5);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (87,'Toulouse','Clube europeu','PSG',3);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (88,'Amiens','Clube europeu','PSG',2);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (89,'Dijon','Clube europeu','PSG',3);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (90,'Montpellier','Clube europeu','PSG',4);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (91,'Angers','Clube europeu','PSG',2);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (92,'Metz','Clube europeu','PSG',2);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (93,'Nantes','Clube europeu','PSG',2);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (94,'Saint-Étienne','Clube europeu','PSG',2);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (95,'Caen','Clube europeu','PSG',1);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (96,'Strasbourg','Clube europeu','PSG',1);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (97,'Manchester United','Clube europeu','PSG',3);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (98,'Liverpool','Clube europeu','PSG',1);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (99,'Istanbul Başakşehir','Clube europeu','PSG',3);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (100,'Estrela Vermelha','Clube europeu','PSG',3);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (101,'RB Leipzig','Clube europeu','PSG',1);
insert into public.neymar_opponents (sort_order,name,category,context,goals) values (102,'Nassaji Mazandaran','Clube asiático','Al-Hilal',1);
insert into public.neymar_gallery (sort_order,title,tag,image,credit) values (1,'Neymar no auge pelo Barcelona','Barcelona','https://commons.wikimedia.org/wiki/Special:FilePath/Neymar%20-%20FC%20Barcelona%20-%202015.jpg','Wikimedia Commons / Alex Fau');
insert into public.neymar_gallery (sort_order,title,tag,image,credit) values (2,'Apresentação no Barcelona','Barcelona','https://commons.wikimedia.org/wiki/Special:FilePath/Neymar%20Barcelona%20presentation%202.jpg','Wikimedia Commons');
insert into public.neymar_gallery (sort_order,title,tag,image,credit) values (3,'Brasil e ouro olímpico','Seleção','https://commons.wikimedia.org/wiki/Special:FilePath/Neymar%20Rio%202016.jpg','Agência Brasil / Wikimedia Commons');
insert into public.neymar_gallery (sort_order,title,tag,image,credit) values (4,'Neymar pela Seleção','Seleção','https://commons.wikimedia.org/wiki/Special:FilePath/Neymar%20contra%20uruguai.jpg','Wikimedia Commons');
insert into public.neymar_gallery (sort_order,title,tag,image,credit) values (5,'Camisa do PSG','PSG','https://commons.wikimedia.org/wiki/Special:FilePath/Neymar%20PSG.jpg','Wikimedia Commons');
insert into public.neymar_gallery (sort_order,title,tag,image,credit) values (6,'Troféu Champions League','Troféu','https://commons.wikimedia.org/wiki/Special:FilePath/Champions%20League%20Trophy%20%2852736201132%29.jpg','Wikimedia Commons');
insert into public.neymar_gallery (sort_order,title,tag,image,credit) values (7,'Troféu Libertadores','Troféu','https://commons.wikimedia.org/wiki/Special:FilePath/Trof%C3%A9u%20da%20Copa%20Libertadores%20da%20Am%C3%A9rica%20de%202023.jpg','Wikimedia Commons');
insert into public.neymar_gallery (sort_order,title,tag,image,credit) values (8,'Copa das Confederações 2013','Seleção','https://commons.wikimedia.org/wiki/Special:FilePath/Confed.Cup2013Champions.jpg','Wikimedia Commons');
insert into public.neymar_sources (sort_order,label,url) values (1,'Transfermarkt — Perfil, gols, pênaltis e conquistas','https://www.transfermarkt.com/neymar');
insert into public.neymar_sources (sort_order,label,url) values (2,'StatBunker — tipos de gol por pé, cabeça, falta e pênalti','https://www.statbunker.com/players/getPlayerStats?player_id=37759');
insert into public.neymar_sources (sort_order,label,url) values (3,'Wikimedia Commons — imagens reais em licenças abertas','https://commons.wikimedia.org/wiki/Neymar');
insert into public.neymar_sources (sort_order,label,url) values (4,'Wikipedia — títulos e estatísticas gerais','https://pt.wikipedia.org/wiki/Neymar');

-- Pronto. Agora abra o GitHub Pages e a aba Supabase para verificar a conexão.